### ISSUE TITLE
Issue with nginx limit_except

### ISSUE THREAD

**Issue by The-Don-Himself** [slact/nchan#348]
I am seeing an issue when nchan is used with nginx's limit_except and basic auth

For example

````
        location ~ /tests/(.*)$ {
            limit_except GET {
                auth_basic           "Administrator’s Area";
                auth_basic_user_file /etc/nginx/.htpasswd; 
            }
            nchan_pubsub;
            nchan_channel_id "$1";
            nchan_channel_id_split_delimiter ",";
        }
````

this consistently leads to a 404 error, while removing the limit_except block allows Nchan to function.

**Comment by slact** [comment]
I'm not seeing any problem using the `limit_except` directive for publishing or subscribing. Can you be more specific about what happens?

What request do you need to send to the /tests/.* location to get a 404? What's in your error and access logs as a result of this request?

**Comment by The-Don-Himself** [comment]
This happens on vanilla installs on both my production server Centos 7.3 with latest Nchan and dev machine windows 7 cygwin 64 latest with nchan 1.0.8

The requests I'm sending are the exact "test message" as in the docs.

What happens 
````
requesting the endpoint asks for a password - correct expected behavior
requesting the endpoint with wrong password access denied - correct expected behavior
requesting the endpoint with right password 404 not found - incorrect expected behavior
requesting the endpoint without limit_except pubsub established - correct expected behavior
````
So far nothing in the logs other than 404 not found, if there is somewhere else you can point me at I will take a look and give feedback, currently I am using this workaround

````
http {

    #....

    geo $allowed_post_put {
        default 0;
        127.0.0.1 1;
        ::1 1;
        111.222.333.444 1;
    }

    map $request_method:$allowed_post_put $return_405 {
        "POST:0" 1; 
        "PUT:0" 1;
        "DELETE:0" 1;
    }

    #....

    server {

        #....

		location ~ /tests/(.*)$ {
            if ( $return_405 = 1 ) {
                return 405;
            }
			nchan_pubsub;
			nchan_channel_id "$1";
			nchan_channel_id_split_delimiter ",";
		}

        #....

    }

}
````

**Comment by slact** [comment]
Looks like `limit_except` is implemented rather weirdly, and ends up [overriding](http://lxr.nginx.org/source/src/http/ngx_http_core_module.c#1437) Nchan's module hooks.
*Challenge Accepted, `limit_except`.*

**Comment by The-Don-Himself** [comment]
You seemed to have found the root cause rather quick thanks!

**Comment by slact** [comment]
Fixed in 79200b34. Please rebuild from master and verify that it's fixed for you as well.

**Comment by The-Don-Himself** [comment]
Unfortunately I am still getting the 404 errors. Rebuilt and tested it twice.

````
git clone https://github.com/slact/nchan.git --branch master
````
Nginx 1.13.0

**Comment by slact** [comment]
Oh, yeah. Looks like my testing wasn't complete. Sorry about that. Double-fixed in 631b9e1cfe7cfa69ca.

**Comment by The-Don-Himself** [comment]
Thanks the latest fix definitely solves it, bravo!
